<?php

namespace Database\Seeders;

use App\Models\Emiten;
use Illuminate\Database\Seeder;

class EmitenSeeder extends Seeder
{
    public function run(): void
    {
        $emitens = [
            // Sektor 1: Perbankan & Keuangan
            ['sector_id'=>1,'kode'=>'BBCA','nama'=>'Bank Central Asia'],
            ['sector_id'=>1,'kode'=>'BBRI','nama'=>'Bank Rakyat Indonesia'],
            ['sector_id'=>1,'kode'=>'BMRI','nama'=>'Bank Mandiri'],
            ['sector_id'=>1,'kode'=>'BBNI','nama'=>'Bank Negara Indonesia'],
            ['sector_id'=>1,'kode'=>'BRIS','nama'=>'Bank Syariah Indonesia'],
            ['sector_id'=>1,'kode'=>'MEGA','nama'=>'Bank Mega'],
            ['sector_id'=>1,'kode'=>'BBTN','nama'=>'Bank Tabungan Negara'],
            ['sector_id'=>1,'kode'=>'ARTO','nama'=>'Bank Jago'],
            ['sector_id'=>1,'kode'=>'BBYB','nama'=>'Bank Neo Commerce'],
            ['sector_id'=>1,'kode'=>'BNGA','nama'=>'Bank CIMB Niaga'],
            ['sector_id'=>1,'kode'=>'NISP','nama'=>'Bank OCBC NISP'],
            ['sector_id'=>1,'kode'=>'BDMN','nama'=>'Bank Danamon Indonesia'],
            ['sector_id'=>1,'kode'=>'BTPS','nama'=>'Bank BTPN Syariah'],
            ['sector_id'=>1,'kode'=>'BJBR','nama'=>'Bank Pembangunan Daerah Jawa Barat'],
            ['sector_id'=>1,'kode'=>'BJTM','nama'=>'Bank Pembangunan Daerah Jawa Timur'],
            ['sector_id'=>1,'kode'=>'PNBN','nama'=>'Bank Pan Indonesia'],
            ['sector_id'=>1,'kode'=>'AGRO','nama'=>'Bank Raya Indonesia'],

            // Sektor 2: Telekomunikasi
            ['sector_id'=>2,'kode'=>'TLKM','nama'=>'Telkom Indonesia'],
            ['sector_id'=>2,'kode'=>'EXCL','nama'=>'XL Axiata'],
            ['sector_id'=>2,'kode'=>'ISAT','nama'=>'Indosat Ooredoo Hutchison'],
            ['sector_id'=>2,'kode'=>'FREN','nama'=>'Smartfren Telecom'],
            ['sector_id'=>2,'kode'=>'MTEL','nama'=>'Dayamitra Telekomunikasi (Mitratel)'],
            ['sector_id'=>2,'kode'=>'TOWR','nama'=>'Sarana Menara Nusantara'],
            ['sector_id'=>2,'kode'=>'TBIG','nama'=>'Tower Bersama Infrastructure'],
            ['sector_id'=>2,'kode'=>'LINK','nama'=>'Link Net'],

            // Sektor 3: Consumer Goods
            ['sector_id'=>3,'kode'=>'UNVR','nama'=>'Unilever Indonesia'],
            ['sector_id'=>3,'kode'=>'ICBP','nama'=>'Indofood CBP Sukses Makmur'],
            ['sector_id'=>3,'kode'=>'INDF','nama'=>'Indofood Sukses Makmur'],
            ['sector_id'=>3,'kode'=>'MYOR','nama'=>'Mayora Indah'],
            ['sector_id'=>3,'kode'=>'GGRM','nama'=>'Gudang Garam'],
            ['sector_id'=>3,'kode'=>'HMSP','nama'=>'H.M. Sampoerna'],
            ['sector_id'=>3,'kode'=>'CPIN','nama'=>'Charoen Pokphand Indonesia'],
            ['sector_id'=>3,'kode'=>'JPFA','nama'=>'Japfa Comfeed Indonesia'],
            ['sector_id'=>3,'kode'=>'MAIN','nama'=>'Malindo Feedmill'],
            ['sector_id'=>3,'kode'=>'ROTI','nama'=>'Nippon Indosari Corpindo'],
            ['sector_id'=>3,'kode'=>'CLEO','nama'=>'Sariguna Primatirta'],
            ['sector_id'=>3,'kode'=>'ULTJ','nama'=>'Ultra Jaya Milk Industry'],
            ['sector_id'=>3,'kode'=>'CMRY','nama'=>'Cisarua Mountain Dairy'],
            ['sector_id'=>3,'kode'=>'KINO','nama'=>'Kino Indonesia'],
            ['sector_id'=>3,'kode'=>'GOOD','nama'=>'Garudafood Putra Putri Jaya'],
            ['sector_id'=>3,'kode'=>'AMRT','nama'=>'Sumber Alfaria Trijaya (Alfamart)'],
            ['sector_id'=>3,'kode'=>'MIDI','nama'=>'Midi Utama Indonesia'],
            ['sector_id'=>3,'kode'=>'MAPI','nama'=>'Mitra Adiperkasa'],
            ['sector_id'=>3,'kode'=>'ERAA','nama'=>'Erajaya Swasembada'],
            ['sector_id'=>3,'kode'=>'ACES','nama'=>'Aces Hardware Indonesia'],

            // Sektor 4: Pertambangan & Logam
            ['sector_id'=>4,'kode'=>'ANTM','nama'=>'Aneka Tambang'],
            ['sector_id'=>4,'kode'=>'AMMN','nama'=>'Amman Mineral Internasional'],
            ['sector_id'=>4,'kode'=>'BRMS','nama'=>'Bumi Resources Minerals'],
            ['sector_id'=>4,'kode'=>'MDKA','nama'=>'Merdeka Copper Gold'],
            ['sector_id'=>4,'kode'=>'INCO','nama'=>'Vale Indonesia'],
            ['sector_id'=>4,'kode'=>'TINS','nama'=>'Timah'],
            ['sector_id'=>4,'kode'=>'MBMA','nama'=>'Merdeka Battery Materials'],
            ['sector_id'=>4,'kode'=>'NCKL','nama'=>'Trimegah Bangun Persada'],
            ['sector_id'=>4,'kode'=>'CUAN','nama'=>'Petrindo Semesta Kreasi'],

            // Sektor 5: Teknologi
            ['sector_id'=>5,'kode'=>'GOTO','nama'=>'GoTo Gojek Tokopedia'],
            ['sector_id'=>5,'kode'=>'BUKA','nama'=>'Bukalapak.com'],
            ['sector_id'=>5,'kode'=>'EMTK','nama'=>'Elang Mahkota Teknologi'],
            ['sector_id'=>5,'kode'=>'WIRG','nama'=>'WIR ASIA'],
            ['sector_id'=>5,'kode'=>'BELI','nama'=>'Global Digital Niaga (Blibli)'],
            ['sector_id'=>5,'kode'=>'MLPT','nama'=>'Multipolar Technology'],
            ['sector_id'=>5,'kode'=>'WIFI','nama'=>'Solusi Sinergi Digital'],
            ['sector_id'=>5,'kode'=>'MTMT','nama'=>'Mitra Telekomunikasi'],

            // Sektor 6: Properti & Real Estate
            ['sector_id'=>6,'kode'=>'BSDE','nama'=>'Bumi Serpong Damai'],
            ['sector_id'=>6,'kode'=>'CTRA','nama'=>'Ciputra Development'],
            ['sector_id'=>6,'kode'=>'SMRA','nama'=>'Summarecon Agung'],
            ['sector_id'=>6,'kode'=>'PWON','nama'=>'Pakuwon Jati'],
            ['sector_id'=>6,'kode'=>'ASRI','nama'=>'Alam Sutera Realty'],
            ['sector_id'=>6,'kode'=>'DILD','nama'=>'Intiland Development'],
            ['sector_id'=>6,'kode'=>'KIJA','nama'=>'Kawasan Industri Jababeka'],
            ['sector_id'=>6,'kode'=>'SSIA','nama'=>'Surya Semesta Internusa'],
            ['sector_id'=>6,'kode'=>'APLN','nama'=>'Agung Podomoro Land'],
            ['sector_id'=>6,'kode'=>'LPKR','nama'=>'Lippo Karawaci'],

            // Sektor 7: Energi & Batu Bara
            ['sector_id'=>7,'kode'=>'ADRO','nama'=>'Adaro Energy Indonesia'],
            ['sector_id'=>7,'kode'=>'PTBA','nama'=>'Bukit Asam'],
            ['sector_id'=>7,'kode'=>'ITMG','nama'=>'Indo Tambangraya Megah'],
            ['sector_id'=>7,'kode'=>'HRUM','nama'=>'Harum Energy'],
            ['sector_id'=>7,'kode'=>'PGAS','nama'=>'Perusahaan Gas Negara'],
            ['sector_id'=>7,'kode'=>'AKRA','nama'=>'AKR Corporindo'],
            ['sector_id'=>7,'kode'=>'MEDC','nama'=>'Medco Energi Internasional'],
            ['sector_id'=>7,'kode'=>'BUMI','nama'=>'Bumi Resources'],
            ['sector_id'=>7,'kode'=>'ENRG','nama'=>'Energi Mega Persada'],
            ['sector_id'=>7,'kode'=>'BYAN','nama'=>'Bayan Resources'],
            ['sector_id'=>7,'kode'=>'RAJA','nama'=>'Rukun Raharja'],
            ['sector_id'=>7,'kode'=>'DOID','nama'=>'Delta Dunia Makmur'],
            ['sector_id'=>7,'kode'=>'PGEO','nama'=>'Pertamina Geothermal Energy'],

            // Sektor 8: Infrastruktur & Konstruksi
            ['sector_id'=>8,'kode'=>'WIKA','nama'=>'Wijaya Karya'],
            ['sector_id'=>8,'kode'=>'JSMR','nama'=>'Jasa Marga'],
            ['sector_id'=>8,'kode'=>'PTPP','nama'=>'PP (Persero)'],
            ['sector_id'=>8,'kode'=>'WSKT','nama'=>'Waskita Karya'],
            ['sector_id'=>8,'kode'=>'ADHI','nama'=>'Adhi Karya'],
            ['sector_id'=>8,'kode'=>'WEGE','nama'=>'Wijaya Karya Bangunan Gedung'],
            ['sector_id'=>8,'kode'=>'TOTL','nama'=>'Total Bangun Persada'],
            ['sector_id'=>8,'kode'=>'CMNP','nama'=>'Citra Marga Nusaphala Persada'],

            // Sektor 9: Healthcare / Kesehatan
            ['sector_id'=>9,'kode'=>'KLBF','nama'=>'Kalbe Farma'],
            ['sector_id'=>9,'kode'=>'SIDO','nama'=>'Industri Jamu Dan Farmasi Sido Muncul'],
            ['sector_id'=>9,'kode'=>'MIKA','nama'=>'Mitra Keluarga Karyasehat'],
            ['sector_id'=>9,'kode'=>'HEAL','nama'=>'Medikaloka Hermina'],
            ['sector_id'=>9,'kode'=>'SILO','nama'=>'Siloam International Hospitals'],
            ['sector_id'=>9,'kode'=>'PRDA','nama'=>'Prodia Widyahusada'],
            ['sector_id'=>9,'kode'=>'KAEF','nama'=>'Kimia Farma'],
            ['sector_id'=>9,'kode'=>'INAF','nama'=>'Indofarma'],
            ['sector_id'=>9,'kode'=>'TSPC','nama'=>'Tempo Scan Pacific'],

            // Sektor 10: Otomotif & Komponen
            ['sector_id'=>10,'kode'=>'ASII','nama'=>'Astra International'],
            ['sector_id'=>10,'kode'=>'AUTO','nama'=>'Astra Otoparts'],
            ['sector_id'=>10,'kode'=>'IMAS','nama'=>'Indomobil Sukses Internasional'],
            ['sector_id'=>10,'kode'=>'GJTL','nama'=>'Gajah Tunggal'],
            ['sector_id'=>10,'kode'=>'SMSM','nama'=>'Selamat Sempurna'],
            ['sector_id'=>10,'kode'=>'DRMA','nama'=>'Dharma Polimetal'],

            // Sektor 11: Media & Hiburan
            ['sector_id'=>11,'kode'=>'SCMA','nama'=>'Surya Citra Media'],
            ['sector_id'=>11,'kode'=>'MNCN','nama'=>'Media Nusantara Citra'],
            ['sector_id'=>11,'kode'=>'FILM','nama'=>'MD Pictures'],
            ['sector_id'=>11,'kode'=>'MSIN','nama'=>'MNC Digital Entertainment'],
            ['sector_id'=>11,'kode'=>'BMTR','nama'=>'Global Mediacom'],
            ['sector_id'=>11,'kode'=>'VIVA','nama'=>'Visi Media Asia'],
            ['sector_id'=>11,'kode'=>'MARI','nama'=>'Mahaka Radio Integra'],

            // Sektor 12: Transportasi & Logistik
            ['sector_id'=>12,'kode'=>'GIAA','nama'=>'Garuda Indonesia'],
            ['sector_id'=>12,'kode'=>'BIRD','nama'=>'Blue Bird'],
            ['sector_id'=>12,'kode'=>'ASLC','nama'=>'Autopedia Sukses Lestari'],
            ['sector_id'=>12,'kode'=>'TMAS','nama'=>'Temas'],
            ['sector_id'=>12,'kode'=>'SMDR','nama'=>'Samudera Indonesia'],
            ['sector_id'=>12,'kode'=>'ASSA','nama'=>'Adi Sarana Armada'],
            ['sector_id'=>12,'kode'=>'CMPP','nama'=>'AirAsia Indonesia'],
            // Sektor Tambahan (13: Berbagai Macam Industri, Barang Konsumsi Non-Primer, dll)
            // Sektor dikelompokkan ke 1-12 yang sudah ada (di-mapping sedekat mungkin)
            ['sector_id'=>8,'kode'=>'SMGR','nama'=>'Semen Indonesia (Persero)'],
            ['sector_id'=>8,'kode'=>'INTP','nama'=>'Indocement Tunggal Prakarsa'],
            ['sector_id'=>8,'kode'=>'SMCB','nama'=>'Solusi Bangun Indonesia'],
            ['sector_id'=>8,'kode'=>'WTON','nama'=>'Wijaya Karya Beton'],
            ['sector_id'=>8,'kode'=>'PTPP','nama'=>'PP Presisi'],
            ['sector_id'=>8,'kode'=>'NRCA','nama'=>'Nusa Raya Cipta'],
            ['sector_id'=>7,'kode'=>'INDY','nama'=>'Indika Energy'],
            ['sector_id'=>7,'kode'=>'TOBA','nama'=>'TBS Energi Utama'],
            ['sector_id'=>7,'kode'=>'PTRO','nama'=>'Petrosea'],
            ['sector_id'=>7,'kode'=>'GEMS','nama'=>'Golden Energy Mines'],
            ['sector_id'=>7,'kode'=>'ABMM','nama'=>'ABM Investama'],
            ['sector_id'=>7,'kode'=>'MBAP','nama'=>'Mitrabara Adiperdana'],
            ['sector_id'=>7,'kode'=>'KKGI','nama'=>'Resource Alam Indonesia'],
            ['sector_id'=>4,'kode'=>'BRPT','nama'=>'Barito Pacific'],
            ['sector_id'=>4,'kode'=>'TPIA','nama'=>'Chandra Asri Pacific'],
            ['sector_id'=>4,'kode'=>'ESSA','nama'=>'ESSA Industries Indonesia'],
            ['sector_id'=>3,'kode'=>'AALI','nama'=>'Astra Agro Lestari'],
            ['sector_id'=>3,'kode'=>'LSIP','nama'=>'PP London Sumatra Indonesia'],
            ['sector_id'=>3,'kode'=>'SIMP','nama'=>'Salim Ivomas Pratama'],
            ['sector_id'=>3,'kode'=>'SSMS','nama'=>'Sawit Sumbermas Sarana'],
            ['sector_id'=>3,'kode'=>'DSNG','nama'=>'Dharma Satya Nusantara'],
            ['sector_id'=>3,'kode'=>'TBLA','nama'=>'Tunas Baru Lampung'],
            ['sector_id'=>3,'kode'=>'CPRO','nama'=>'Central Proteina Prima'],
            ['sector_id'=>3,'kode'=>'HOKI','nama'=>'Buyung Poetra Sembada'],
            ['sector_id'=>3,'kode'=>'AISA','nama'=>'FKS Food Sejahtera'],
            ['sector_id'=>3,'kode'=>'CEKA','nama'=>'Wilmar Cahaya Indonesia'],
            ['sector_id'=>3,'kode'=>'ROTI','nama'=>'Nippon Indosari Corpindo'],
            ['sector_id'=>1,'kode'=>'BFIN','nama'=>'BFI Finance Indonesia'],
            ['sector_id'=>1,'kode'=>'CFIN','nama'=>'Clipan Finance Indonesia'],
            ['sector_id'=>1,'kode'=>'WOMF','nama'=>'Wahana Ottomitra Multiartha'],
            ['sector_id'=>1,'kode'=>'PNLF','nama'=>'Panin Financial'],
            ['sector_id'=>1,'kode'=>'PNIN','nama'=>'Paninvest'],
            ['sector_id'=>1,'kode'=>'BBHI','nama'=>'Allo Bank Indonesia'],
            ['sector_id'=>1,'kode'=>'BABP','nama'=>'Bank MNC Internasional'],
            ['sector_id'=>1,'kode'=>'SDRA','nama'=>'Bank Woori Saudara Indonesia'],
            ['sector_id'=>6,'kode'=>'DART','nama'=>'Duta Anggada Realty'],
            ['sector_id'=>6,'kode'=>'COWL','nama'=>'Cowell Development'],
            ['sector_id'=>6,'kode'=>'MDLN','nama'=>'Modernland Realty'],
            ['sector_id'=>6,'kode'=>'BEST','nama'=>'Bekasi Fajar Industrial Estate'],
            ['sector_id'=>6,'kode'=>'LPCK','nama'=>'Lippo Cikarang'],
            ['sector_id'=>6,'kode'=>'GMTD','nama'=>'Gowa Makassar Tourism Development'],
            ['sector_id'=>12,'kode'=>'ELSA','nama'=>'Elnusa'],
            ['sector_id'=>12,'kode'=>'SOCI','nama'=>'Soechi Lines'],
            ['sector_id'=>12,'kode'=>'WINS','nama'=>'Wintermar Offshore Marine'],
            ['sector_id'=>12,'kode'=>'TPMA','nama'=>'Trans Power Marine'],
            ['sector_id'=>12,'kode'=>'CASS','nama'=>'Cardig Aero Services'],
            ['sector_id'=>5,'kode'=>'DMMX','nama'=>'Digital Mediatama Maxima'],
            ['sector_id'=>5,'kode'=>'KIOS','nama'=>'Kioson Komersial Indonesia'],
            ['sector_id'=>5,'kode'=>'DIVA','nama'=>'Distribusi Voucher Nusantara'],
            ['sector_id'=>5,'kode'=>'LUCK','nama'=>'Sentral Mitra Informatika'],
            ['sector_id'=>5,'kode'=>'TFAS','nama'=>'Telefast Indonesia'],
            ['sector_id'=>10,'kode'=>'IMPC','nama'=>'Impack Pratama Industri'],
            ['sector_id'=>10,'kode'=>'TRIS','nama'=>'Trisula International'],
            ['sector_id'=>10,'kode'=>'RICY','nama'=>'Ricky Putra Globalindo'],
            ['sector_id'=>10,'kode'=>'SRIL','nama'=>'Sri Rejeki Isman'],
            ['sector_id'=>11,'kode'=>'ABBA','nama'=>'Mahaka Media'],
            ['sector_id'=>11,'kode'=>'KREN','nama'=>'Kresna Graha Investama'],
            ['sector_id'=>9,'kode'=>'SAME','nama'=>'Sarana Meditama Metropolitan'],
            ['sector_id'=>9,'kode'=>'CARE','nama'=>'Metro Healthcare Indonesia'],

            // === GELOMBANG 3: Tambahan 100+ Emiten Baru ===
            
            // Sektor 1: Keuangan Tambahan
            ['sector_id'=>1,'kode'=>'BGTG','nama'=>'Bank Ganesha'],
            ['sector_id'=>1,'kode'=>'BCIC','nama'=>'Bank JTrust Indonesia'],
            ['sector_id'=>1,'kode'=>'BINA','nama'=>'Bank Ina Perdana'],
            ['sector_id'=>1,'kode'=>'BSIM','nama'=>'Bank Sinarmas'],
            ['sector_id'=>1,'kode'=>'INPC','nama'=>'Bank Artha Graha Internasional'],
            ['sector_id'=>1,'kode'=>'MAYA','nama'=>'Bank Mayapada Internasional'],
            ['sector_id'=>1,'kode'=>'MCOR','nama'=>'Bank China Construction Bank'],
            ['sector_id'=>1,'kode'=>'PNBS','nama'=>'Bank Panin Dubai Syariah'],
            ['sector_id'=>1,'kode'=>'AMAR','nama'=>'Bank Amar Indonesia'],
            ['sector_id'=>1,'kode'=>'BACA','nama'=>'Bank Capital Indonesia'],
            ['sector_id'=>1,'kode'=>'BBKP','nama'=>'Bank KB Bukopin'],
            ['sector_id'=>1,'kode'=>'DNAR','nama'=>'Bank Oke Indonesia'],
            ['sector_id'=>1,'kode'=>'NOBU','nama'=>'Bank Nationalnobu'],
            ['sector_id'=>1,'kode'=>'AGAN','nama'=>'Binaartha Sekuritas'],
            ['sector_id'=>1,'kode'=>'TRIM','nama'=>'Trimegah Sekuritas'],
            ['sector_id'=>1,'kode'=>'YULE','nama'=>'Yule Sekurindo'],

            // Sektor 2 & 5: Tech & Infrastruktur Telekomunikasi
            ['sector_id'=>2,'kode'=>'GHON','nama'=>'Gihon Telekomunikasi Indonesia'],
            ['sector_id'=>2,'kode'=>'SUPR','nama'=>'Solusi Tunas Pratama'],
            ['sector_id'=>2,'kode'=>'CENT','nama'=>'Centratama Telekomunikasi Indonesia'],
            ['sector_id'=>5,'kode'=>'ATIC','nama'=>'Anabatic Technologies'],
            ['sector_id'=>5,'kode'=>'GLVA','nama'=>'Galva Technologies'],
            ['sector_id'=>5,'kode'=>'MTDL','nama'=>'Metrodata Electronics'],
            ['sector_id'=>5,'kode'=>'PTSN','nama'=>'Sat Nusapersada'],
            ['sector_id'=>5,'kode'=>'MCAS','nama'=>'M Cash Integrasi'],
            ['sector_id'=>5,'kode'=>'NFCX','nama'=>'NFC Indonesia'],
            ['sector_id'=>5,'kode'=>'JAST','nama'=>'Jasnita Telekomindo'],
            ['sector_id'=>5,'kode'=>'ZYRX','nama'=>'Zyrexindo Mandiri Buana'],
            ['sector_id'=>5,'kode'=>'EDGE','nama'=>'Indointernet'],
            ['sector_id'=>5,'kode'=>'AWAN','nama'=>'Era Digital Media'],

            // Sektor 3: Consumer Goods Tambahan
            ['sector_id'=>3,'kode'=>'MLBI','nama'=>'Multi Bintang Indonesia'],
            ['sector_id'=>3,'kode'=>'DLTA','nama'=>'Delta Djakarta'],
            ['sector_id'=>3,'kode'=>'SKLT','nama'=>'Sekar Laut'],
            ['sector_id'=>3,'kode'=>'STTP','nama'=>'Siantar Top'],
            ['sector_id'=>3,'kode'=>'TOTO','nama'=>'Surya Toto Indonesia'],
            ['sector_id'=>3,'kode'=>'TCID','nama'=>'Mandom Indonesia'],
            ['sector_id'=>3,'kode'=>'WOOD','nama'=>'Integra Indocabinet'],
            ['sector_id'=>3,'kode'=>'WIIM','nama'=>'Wismilak Inti Makmur'],
            ['sector_id'=>3,'kode'=>'RMBA','nama'=>'Bentoel International Investama'],
            ['sector_id'=>3,'kode'=>'ALTO','nama'=>'Tri Banyan Tirta'],
            ['sector_id'=>3,'kode'=>'CAMP','nama'=>'Campina Ice Cream Industry'],
            ['sector_id'=>3,'kode'=>'CLEO','nama'=>'Sariguna Primatirta'],
            ['sector_id'=>3,'kode'=>'FOOD','nama'=>'Sentra Food Indonesia'],
            ['sector_id'=>3,'kode'=>'KEJU','nama'=>'Mulia Boga Raya'],

            // Sektor 4 & 7: Tambang & Energi Tambahan
            ['sector_id'=>4,'kode'=>'BSSR','nama'=>'Baramulti Suksessarana'],
            ['sector_id'=>4,'kode'=>'SMMT','nama'=>'Golden Eagle Energy'],
            ['sector_id'=>4,'kode'=>'ARII','nama'=>'Atlas Resources'],
            ['sector_id'=>4,'kode'=>'DEWA','nama'=>'Darma Henwa'],
            ['sector_id'=>4,'kode'=>'RUIS','nama'=>'Radiant Utama Interinsco'],
            ['sector_id'=>4,'kode'=>'TRAM','nama'=>'Trada Alam Minera'],
            ['sector_id'=>7,'kode'=>'BIPI','nama'=>'Astrindo Nusantara Infrastruktur'],
            ['sector_id'=>7,'kode'=>'APEX','nama'=>'Apexindo Pratama Duta'],
            ['sector_id'=>7,'kode'=>'LEAD','nama'=>'Logindo Samudramakmur'],
            ['sector_id'=>7,'kode'=>'ENRG','nama'=>'Energi Mega Persada'],
            ['sector_id'=>7,'kode'=>'PKPK','nama'=>'Perdana Karya Perkasa'],

            // Sektor 6: Properti Tambahan
            ['sector_id'=>6,'kode'=>'BKSL','nama'=>'Sentul City'],
            ['sector_id'=>6,'kode'=>'DUTI','nama'=>'Duta Pertiwi'],
            ['sector_id'=>6,'kode'=>'FMII','nama'=>'Fortune Mate Indonesia'],
            ['sector_id'=>6,'kode'=>'GWSA','nama'=>'Greenwood Sejahtera'],
            ['sector_id'=>6,'kode'=>'JRPT','nama'=>'Jaya Real Property'],
            ['sector_id'=>6,'kode'=>'MTLA','nama'=>'Metropolitan Land'],
            ['sector_id'=>6,'kode'=>'NIRO','nama'=>'City Retail Developments'],
            ['sector_id'=>6,'kode'=>'PLIN','nama'=>'Plaza Indonesia Realty'],
            ['sector_id'=>6,'kode'=>'BAPA','nama'=>'Bekasi Asri Pemula'],
            ['sector_id'=>6,'kode'=>'OMRE','nama'=>'Indonesia Prima Property'],

            // Sektor 8: Infrastruktur & Konstruksi Tambahan
            ['sector_id'=>8,'kode'=>'ACST','nama'=>'Acset Indonusa'],
            ['sector_id'=>8,'kode'=>'DGIK','nama'=>'Nusa Konstruksi Enjiniring'],
            ['sector_id'=>8,'kode'=>'PBSA','nama'=>'Paramita Bangun Sarana'],
            ['sector_id'=>8,'kode'=>'JKON','nama'=>'Jaya Konstruksi'],
            ['sector_id'=>8,'kode'=>'IDPR','nama'=>'Indonesia Pondasi Raya'],
            ['sector_id'=>8,'kode'=>'VOKS','nama'=>'Voksel Electric'],
            ['sector_id'=>8,'kode'=>'BUKK','nama'=>'Bukaka Teknik Utama'],
            ['sector_id'=>8,'kode'=>'META','nama'=>'Nusantara Infrastructure'],
            ['sector_id'=>8,'kode'=>'CITA','nama'=>'Cita Mineral Investindo'],

            // Sektor 9: Healthcare Tambahan
            ['sector_id'=>9,'kode'=>'BMHS','nama'=>'Bundamedik'],
            ['sector_id'=>9,'kode'=>'OMNI','nama'=>'Sarana Meditama Metropolitan'],
            ['sector_id'=>9,'kode'=>'RSGK','nama'=>'Kedoya Adyaraya'],
            ['sector_id'=>9,'kode'=>'SRAJ','nama'=>'Sejahteraraya Anugrahjaya'],
            ['sector_id'=>9,'kode'=>'PEHA','nama'=>'Phapros'],
            ['sector_id'=>9,'kode'=>'PYFA','nama'=>'Pyridam Farma'],
            ['sector_id'=>9,'kode'=>'SOHO','nama'=>'Soho Global Health'],

            // Sektor 10: Industri / Manufaktur Tambahan
            ['sector_id'=>10,'kode'=>'LPIN','nama'=>'Multi Prima Sejahtera'],
            ['sector_id'=>10,'kode'=>'MASA','nama'=>'Multistrada Arah Sarana'],
            ['sector_id'=>10,'kode'=>'NIPS','nama'=>'Nipress'],
            ['sector_id'=>10,'kode'=>'PRAS','nama'=>'Prima Alloy Steel Universal'],
            ['sector_id'=>10,'kode'=>'BOLT','nama'=>'Garuda Metalindo'],
            ['sector_id'=>10,'kode'=>'BRAM','nama'=>'Indo Kordsa'],
            ['sector_id'=>10,'kode'=>'GDYR','nama'=>'Goodyear Indonesia'],

            // Sektor 11: Media Tambahan
            ['sector_id'=>11,'kode'=>'BLTZ','nama'=>'Graha Layar Prima'],
            ['sector_id'=>11,'kode'=>'JTPE','nama'=>'Jasuindo Tiga Perkasa'],
            ['sector_id'=>11,'kode'=>'MDIA','nama'=>'Intermedia Capital'],
            ['sector_id'=>11,'kode'=>'MSKY','nama'=>'MNC Sky Vision'],
            ['sector_id'=>11,'kode'=>'TMPO','nama'=>'Tempo Inti Media'],
            ['sector_id'=>11,'kode'=>'ZBRA','nama'=>'Dosni Roha Indonesia'],

            // Sektor 12: Transportasi Tambahan
            ['sector_id'=>12,'kode'=>'BPTR','nama'=>'Batavia Prosperindo Trans'],
            ['sector_id'=>12,'kode'=>'HITS','nama'=>'Humpuss Intermoda Transportasi'],
            ['sector_id'=>12,'kode'=>'IATA','nama'=>'Indonesia Transport & Infrastructure'],
            ['sector_id'=>12,'kode'=>'IPCM','nama'=>'Jasa Armada Indonesia'],
            ['sector_id'=>12,'kode'=>'NELY','nama'=>'Pelayaran Nelly Dwi Putri'],
            ['sector_id'=>12,'kode'=>'PANI','nama'=>'Pantai Indah Kapuk Dua'],
            ['sector_id'=>12,'kode'=>'PTIS','nama'=>'Indo Straits'],
            ['sector_id'=>12,'kode'=>'RIGS','nama'=>'Rig Tenders Indonesia'],
            ['sector_id'=>12,'kode'=>'TRUK','nama'=>'Guna Timur Raya'],
            ['sector_id'=>12,'kode'=>'WEHA','nama'=>'WEHA Transportasi Indonesia'],
            ['sector_id'=>12,'kode'=>'WEHA','nama'=>'WEHA Transportasi Indonesia'],

            // === GELOMBANG 4: Tambahan 150+ Emiten Baru ===
            
            // Sektor 1: Keuangan (Finance)
            ['sector_id'=>1,'kode'=>'AMOR','nama'=>'Ashmore Asset Management'],
            ['sector_id'=>1,'kode'=>'APIC','nama'=>'Pacific Strategic Financial'],
            ['sector_id'=>1,'kode'=>'BKSW','nama'=>'Bank QNB Indonesia'],
            ['sector_id'=>1,'kode'=>'BMAS','nama'=>'Bank Maspion Indonesia'],
            ['sector_id'=>1,'kode'=>'BNBA','nama'=>'Bank Bumi Arta'],
            ['sector_id'=>1,'kode'=>'BPFI','nama'=>'Batavia Prosperindo Finance'],
            ['sector_id'=>1,'kode'=>'BTPN','nama'=>'Bank BTPN'],
            ['sector_id'=>1,'kode'=>'BVIC','nama'=>'Bank Victoria International'],
            ['sector_id'=>1,'kode'=>'CASA','nama'=>'Capital Financial Indonesia'],
            ['sector_id'=>1,'kode'=>'DEFI','nama'=>'Danasupra Erapacific'],
            ['sector_id'=>1,'kode'=>'FUJI','nama'=>'Fuji Finance Indonesia'],
            ['sector_id'=>1,'kode'=>'GSMF','nama'=>'Equity Development Investment'],
            ['sector_id'=>1,'kode'=>'LPPS','nama'=>'Lippo Securities'],
            ['sector_id'=>1,'kode'=>'MFIN','nama'=>'Mandala Multifinance'],
            ['sector_id'=>1,'kode'=>'PANS','nama'=>'Panin Sekuritas'],
            ['sector_id'=>1,'kode'=>'PNIN','nama'=>'Paninvest'],
            ['sector_id'=>1,'kode'=>'POLA','nama'=>'Pool Advista Finance'],
            ['sector_id'=>1,'kode'=>'RELI','nama'=>'Reliance Sekuritas Indonesia'],
            ['sector_id'=>1,'kode'=>'SMMA','nama'=>'Sinarmas Multiartha'],
            ['sector_id'=>1,'kode'=>'TRUS','nama'=>'Trust Finance Indonesia'],
            ['sector_id'=>1,'kode'=>'VINS','nama'=>'Victoria Investama'],
            ['sector_id'=>1,'kode'=>'VIVA','nama'=>'Visi Media Asia'],

            // Sektor 3: Consumer Goods
            ['sector_id'=>3,'kode'=>'ADES','nama'=>'Akasha Wira International'],
            ['sector_id'=>3,'kode'=>'BTEK','nama'=>'Bumi Teknokultura Utama'],
            ['sector_id'=>3,'kode'=>'BUDI','nama'=>'Budi Starch & Sweetener'],
            ['sector_id'=>3,'kode'=>'CINT','nama'=>'Chitose Internasional'],
            ['sector_id'=>3,'kode'=>'DAVO','nama'=>'Davomas Abadi'],
            ['sector_id'=>3,'kode'=>'ENZO','nama'=>'Morenzo Abadi Perkasa'],
            ['sector_id'=>3,'kode'=>'GZCO','nama'=>'Gozco Plantations'],
            ['sector_id'=>3,'kode'=>'HRTA','nama'=>'Hartadinata Abadi'],
            ['sector_id'=>3,'kode'=>'ICBP','nama'=>'Indofood CBP Sukses Makmur'],
            ['sector_id'=>3,'kode'=>'INDF','nama'=>'Indofood Sukses Makmur'],
            ['sector_id'=>3,'kode'=>'JAWA','nama'=>'Jaya Agra Wattie'],
            ['sector_id'=>3,'kode'=>'KINO','nama'=>'Kino Indonesia'],
            ['sector_id'=>3,'kode'=>'KPIG','nama'=>'MNC Land'],
            ['sector_id'=>3,'kode'=>'MAGP','nama'=>'Multi Agro Gemilang Plantation'],
            ['sector_id'=>3,'kode'=>'MAPI','nama'=>'Mitra Adiperkasa'],
            ['sector_id'=>3,'kode'=>'MBTO','nama'=>'Martina Berto'],
            ['sector_id'=>3,'kode'=>'MRAT','nama'=>'Mustika Ratu'],
            ['sector_id'=>3,'kode'=>'MYOR','nama'=>'Mayora Indah'],
            ['sector_id'=>3,'kode'=>'PCAR','nama'=>'Prima Cakrawala Abadi'],
            ['sector_id'=>3,'kode'=>'PSGO','nama'=>'Palma Serasih'],
            ['sector_id'=>3,'kode'=>'SGER','nama'=>'Sumber Global Energy'],
            ['sector_id'=>3,'kode'=>'SKBM','nama'=>'Sekar Bumi'],
            ['sector_id'=>3,'kode'=>'SULI','nama'=>'SLJ Global'],
            ['sector_id'=>3,'kode'=>'TBLA','nama'=>'Tunas Baru Lampung'],
            ['sector_id'=>3,'kode'=>'ULTJ','nama'=>'Ultrajaya Milk Industry'],
            ['sector_id'=>3,'kode'=>'UNVR','nama'=>'Unilever Indonesia'],

            // Sektor 4: Mining
            ['sector_id'=>4,'kode'=>'BUMI','nama'=>'Bumi Resources'],
            ['sector_id'=>4,'kode'=>'BYAN','nama'=>'Bayan Resources'],
            ['sector_id'=>4,'kode'=>'CITA','nama'=>'Cita Mineral Investindo'],
            ['sector_id'=>4,'kode'=>'CTTH','nama'=>'Citatah'],
            ['sector_id'=>4,'kode'=>'DKFT','nama'=>'Central Omega Resources'],
            ['sector_id'=>4,'kode'=>'DOID','nama'=>'Delta Dunia Makmur'],
            ['sector_id'=>4,'kode'=>'GEMS','nama'=>'Golden Energy Mines'],
            ['sector_id'=>4,'kode'=>'HRUM','nama'=>'Harum Energy'],
            ['sector_id'=>4,'kode'=>'INCO','nama'=>'Vale Indonesia'],
            ['sector_id'=>4,'kode'=>'ITMG','nama'=>'Indo Tambangraya Megah'],
            ['sector_id'=>4,'kode'=>'KOBX','nama'=>'Kobexindo Tractors'],
            ['sector_id'=>4,'kode'=>'MDKA','nama'=>'Merdeka Copper Gold'],
            ['sector_id'=>4,'kode'=>'MITI','nama'=>'Mitra Investindo'],
            ['sector_id'=>4,'kode'=>'MYOH','nama'=>'Samindo Resources'],
            ['sector_id'=>4,'kode'=>'PSAB','nama'=>'J Resources Asia Pasifik'],
            ['sector_id'=>4,'kode'=>'PTBA','nama'=>'Bukit Asam'],
            ['sector_id'=>4,'kode'=>'PTRO','nama'=>'Petrosea'],
            ['sector_id'=>4,'kode'=>'TINS','nama'=>'Timah'],
            ['sector_id'=>4,'kode'=>'TOBA','nama'=>'TBS Energi Utama'],
            ['sector_id'=>4,'kode'=>'ZINC','nama'=>'Kapuas Prima Coal'],

            // Sektor 6: Property & Real Estate
            ['sector_id'=>6,'kode'=>'BCIP','nama'=>'Bumi Citra Permai'],
            ['sector_id'=>6,'kode'=>'BIPP','nama'=>'Bhuwanatala Indah Permai'],
            ['sector_id'=>6,'kode'=>'BKDP','nama'=>'Bukit Darmo Property'],
            ['sector_id'=>6,'kode'=>'BSDE','nama'=>'Bumi Serpong Damai'],
            ['sector_id'=>6,'kode'=>'CTRA','nama'=>'Ciputra Development'],
            ['sector_id'=>6,'kode'=>'EMDE','nama'=>'Megapolitan Developments'],
            ['sector_id'=>6,'kode'=>'GPRA','nama'=>'Perdana Gapuraprima'],
            ['sector_id'=>6,'kode'=>'KIJA','nama'=>'Kawasan Industri Jababeka'],
            ['sector_id'=>6,'kode'=>'MTSM','nama'=>'Metro Realty'],
            ['sector_id'=>6,'kode'=>'PPRO','nama'=>'PP Properti'],
            ['sector_id'=>6,'kode'=>'RBMS','nama'=>'Ristia Bintang Mahkotasejati'],
            ['sector_id'=>6,'kode'=>'RDTX','nama'=>'Roda Vivatex'],
            ['sector_id'=>6,'kode'=>'ROAM','nama'=>'Pudjiadi Prestige'],
            ['sector_id'=>6,'kode'=>'SMDM','nama'=>'Suryamas Dutamakmur'],
            ['sector_id'=>6,'kode'=>'TARA','nama'=>'Agung Semesta Sejahtera'],
            ['sector_id'=>6,'kode'=>'URBN','nama'=>'Urban Jakarta Propertindo'],

            // Sektor 8: Infrastructure
            ['sector_id'=>8,'kode'=>'BINA','nama'=>'Bank Ina Perdana'],
            ['sector_id'=>8,'kode'=>'CASS','nama'=>'Cardig Aero Services'],
            ['sector_id'=>8,'kode'=>'CMNP','nama'=>'Citra Marga Nusaphala Persada'],
            ['sector_id'=>8,'kode'=>'EXCL','nama'=>'XL Axiata'],
            ['sector_id'=>8,'kode'=>'FREN','nama'=>'Smartfren Telecom'],
            ['sector_id'=>8,'kode'=>'ISAT','nama'=>'Indosat'],
            ['sector_id'=>8,'kode'=>'JSMR','nama'=>'Jasa Marga'],
            ['sector_id'=>8,'kode'=>'KBLI','nama'=>'KMI Wire & Cable'],
            ['sector_id'=>8,'kode'=>'KBLM','nama'=>'Kabelindo Murni'],
            ['sector_id'=>8,'kode'=>'LINK','nama'=>'Link Net'],
            ['sector_id'=>8,'kode'=>'OASA','nama'=>'Maharaksa Biru Energi'],
            ['sector_id'=>8,'kode'=>'PSSI','nama'=>'Pelita Samudera Shipping'],
            ['sector_id'=>8,'kode'=>'PTFC','nama'=>'PT Fajar Surya Wisesa'],
            ['sector_id'=>8,'kode'=>'SCCO','nama'=>'Supreme Cable Manufacturing'],
            ['sector_id'=>8,'kode'=>'TBIG','nama'=>'Tower Bersama Infrastructure'],
            ['sector_id'=>8,'kode'=>'TLKM','nama'=>'Telkom Indonesia'],
            ['sector_id'=>8,'kode'=>'TOWR','nama'=>'Sarana Menara Nusantara'],
            ['sector_id'=>8,'kode'=>'VOKS','nama'=>'Voksel Electric'],

            // Sektor 10: Basic Industry / Manufacturing
            ['sector_id'=>10,'kode'=>'ALDO','nama'=>'Alkindo Naratama'],
            ['sector_id'=>10,'kode'=>'ALMI','nama'=>'Alumindo Light Metal Industry'],
            ['sector_id'=>10,'kode'=>'ARNA','nama'=>'Arwana Citramulia'],
            ['sector_id'=>10,'kode'=>'ASII','nama'=>'Astra International'],
            ['sector_id'=>10,'kode'=>'AUTO','nama'=>'Astra Otoparts'],
            ['sector_id'=>10,'kode'=>'BAJA','nama'=>'Saranacentral Bajatama'],
            ['sector_id'=>10,'kode'=>'BATA','nama'=>'Sepatu Bata'],
            ['sector_id'=>10,'kode'=>'BTON','nama'=>'Betonjaya Manunggal'],
            ['sector_id'=>10,'kode'=>'CPIN','nama'=>'Charoen Pokphand Indonesia'],
            ['sector_id'=>10,'kode'=>'EKAD','nama'=>'Ekadharma International'],
            ['sector_id'=>10,'kode'=>'FASW','nama'=>'Fajar Surya Wisesa'],
            ['sector_id'=>10,'kode'=>'GDST','nama'=>'Gunawan Dianjaya Steel'],
            ['sector_id'=>10,'kode'=>'GJTL','nama'=>'Gajah Tunggal'],
            ['sector_id'=>10,'kode'=>'IGAR','nama'=>'Champion Pacific Indonesia'],
            ['sector_id'=>10,'kode'=>'IMAS','nama'=>'Indomobil Sukses Internasional'],
            ['sector_id'=>10,'kode'=>'INAI','nama'=>'Indal Aluminium Industry'],
            ['sector_id'=>10,'kode'=>'INCI','nama'=>'Intanwijaya Internasional'],
            ['sector_id'=>10,'kode'=>'INDR','nama'=>'Indo-Rama Synthetics'],
            ['sector_id'=>10,'kode'=>'INKP','nama'=>'Indah Kiat Pulp & Paper'],
            ['sector_id'=>10,'kode'=>'INTP','nama'=>'Indocement Tunggal Prakarsa'],
            ['sector_id'=>10,'kode'=>'IPOL','nama'=>'Indopoly Swakarsa Industry'],
            ['sector_id'=>10,'kode'=>'JPFA','nama'=>'Japfa Comfeed Indonesia'],
            ['sector_id'=>10,'kode'=>'KIAS','nama'=>'Keramika Indonesia Assosiasi'],
            ['sector_id'=>10,'kode'=>'KICI','nama'=>'Kedaung Indah Can'],
            ['sector_id'=>10,'kode'=>'KRAS','nama'=>'Krakatau Steel'],
            ['sector_id'=>10,'kode'=>'LION','nama'=>'Lion Metal Works'],
            ['sector_id'=>10,'kode'=>'LMPI','nama'=>'Langgeng Makmur Industri'],
            ['sector_id'=>10,'kode'=>'MAIN','nama'=>'Malindo Feedmill'],
            ['sector_id'=>10,'kode'=>'MERK','nama'=>'Merck'],
            ['sector_id'=>10,'kode'=>'MLIA','nama'=>'Mulia Industrindo'],
            ['sector_id'=>10,'kode'=>'PBRX','nama'=>'Pan Brothers'],
            ['sector_id'=>10,'kode'=>'PICO','nama'=>'Pelangi Indah Canindo'],
            ['sector_id'=>10,'kode'=>'POLY','nama'=>'Asia Pacific Fibers'],
            ['sector_id'=>10,'kode'=>'RICY','nama'=>'Ricky Putra Globalindo'],
            ['sector_id'=>10,'kode'=>'SMCB','nama'=>'Solusi Bangun Indonesia'],
            ['sector_id'=>10,'kode'=>'SMGR','nama'=>'Semen Indonesia'],
            ['sector_id'=>10,'kode'=>'SMSM','nama'=>'Selamat Sempurna'],
            ['sector_id'=>10,'kode'=>'SPMA','nama'=>'Suparma'],
            ['sector_id'=>10,'kode'=>'SRSN','nama'=>'Indo Acidatama'],
            ['sector_id'=>10,'kode'=>'TKIM','nama'=>'Pabrik Kertas Tjiwi Kimia'],
            ['sector_id'=>10,'kode'=>'TPIA','nama'=>'Chandra Asri Pacific'],
            ['sector_id'=>10,'kode'=>'TRST','nama'=>'Trias Sentosa'],
        ];

        foreach ($emitens as $e) {
            // Karena kita hanya define sector_id, kode, dan nama, 
            // biarkan data stat yang lain di-generate dummy (random) untuk radar chartnya
            // (Atau kita sediakan default supaya tidak error jika field null)
            $e['harga'] = 100;
            $e['market_cap'] = rand(5, 500);
            $e['npm'] = rand(-5, 30);
            $e['per'] = rand(5, 45);
            $e['pbv'] = rand(1, 10);
            $e['der'] = rand(0, 3);
            $e['roe'] = rand(-5, 25);
            $e['roa'] = rand(-5, 15);
            $e['dividend_yield'] = rand(0, 8);
            $e['ytd_return'] = rand(-20, 30);
            $e['one_year_return'] = rand(-30, 50);
            $e['three_year_return'] = rand(-50, 100);
            $e['volume'] = rand(1000000, 50000000);

            Emiten::updateOrCreate(['kode' => $e['kode']], $e);
        }
    }
}
